### PR TITLE
fix: adv data donation  

### PR DESCRIPTION
**Pull request by ascariandrea**
In this PR I've only resolved the "real time update" issue with injected components, I did not investigate the issue with adv for now.

@vecna I can leave this here if you want to work on this

### CODE REVIEW

**Comment by vecna** [comment]
has been tested with actual YC advertising? I can make it this evening; if you do it before, please write it here. We should try the process of "I saw an ad" -> "as an user I can make sure the ad was collected"

**Comment by ascariandrea** [comment]
@djfm I think you didn't refresh the extension properly, cause I also updated that component UI

**Comment by vecna** [comment]
TODO from my side:

- [ ] Test it locally, point to localhost,
- [ ] merge this PR,

**Comment by ascariandrea** [comment]
@vecna do you think you can close this today?

**Comment by vecna** [comment]
Yes, I'm testing it now

**Comment by vecna** [comment]
image

sorry but the popup isn't updating switch, when I click it it remains turn-off

**Comment by vecna** [comment]
image
image

**Comment by vecna** [comment]
this bug is preventing me to change the switch 
image

**Comment by vecna** [comment]
This bug happens if you **do not have** youtube.com opened

**Comment by vecna** [comment]
should "ADV Seen" and "Video Sent" .fadeOut after 1500ms ?

**Comment by vecna** [comment]
looks very good thanks. there are two small improvement to be done before the final release, but it is a great progress anyway.

**Pull request merged**
