### PR TITLE
fix: error box

### PR DESCRIPTION
**Pull request by ascariandrea**
I fixed the `ErrorBox` component to proper display error _details_ in the alert and I created a separated box with "debug" info.

We still need a proper error handling to cover any error that may occurre, but that would involve a huge refactor of the API as well.

Screenshot from 2021-11-18 13-38-47

### CODE REVIEW

**Comment by vecna** [comment]
sorry but the conflict about Popup what's due to? which is the right piece of code? thanks

**Comment by ascariandrea** [comment]
I think @spaghettinucleari pushed directly on `daily`   : P

**Comment by vecna** [comment]
testing now, I see the improvement, but also perhaps I overestimate our server-side-errors :) 

image

**Comment by vecna** [comment]
this error happens when backend side a dashboard access without a valid token:

```
  routes:youchoose Invalid token: { error: true, message: 'Not found' }, authorization fail +11ms
  yttrex API (creatorGet) failure, returning 500 +1ms
```

so the server should be more explicit in the message "Token not found" instead of "not found", and I'll review that in the API, but the client should display that message.

**Comment by vecna** [comment]
when this is done it closes #141, plus I'll mention here the review of `backend/routes/youchoose.js` errors

**Review by djfm — APPROVED** [review]

**Pull request merged**
