### PR TITLE
feat: analytics tree map

### PR DESCRIPTION
**Pull request by ascariandrea**
As you can see, the tree map graph component is in place:

Screenshot from 2021-11-22 16-04-17

However I still need to define some of the actions for this graph:
- should I open the link when the user click the `sponsoredName`?
- should I display something on "hover"?

### CODE REVIEW

**Comment by spaghettinucleari** [comment]
The idea was to display over some spec like the number of appearance on hover, what do you think?

**Comment by ascariandrea** [comment]
Ok @spaghettinucleari , is it enough for now? Also cause we don't have other data to display ATM

**Comment by djfm** [comment]
I'm fine with displaying the number on hover, I'd kinda like to have the number expressed in terms of a percentage of the total somewhere though, either in the hover or between parentheses directly in the map, I think it's a rather natural question people ask themselves when they see a distribution of things.

I'm having s slight graphical issue: for me the hover text is displayed way up in the page without any apparent relation to the treemap:
image

Lastly, the responsiveness of the treemap breaks at the lowest breakpoint, but that's not a big deal.

**Comment by spaghettinucleari** [comment]
The treemap is that big cause in the future we would like to have the ad's screenshots?

**Comment by ascariandrea** [comment]
I fixed the tooltip positioning and aligned the submodule.

The graph is that big cause is the first iteration on this. Both data and style need to be reviewed, but since we're moving to yttrex repo we need to merge this.

**Pull request merged**
